# CMake generated Testfile for 
# Source directory: /home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial
# Build directory: /home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/kinsol/serial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(kinAnalytic_fp "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/kinsol/serial/kinAnalytic_fp")
set_tests_properties(kinAnalytic_fp PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;98;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;0;")
add_test(kinAnalytic_fp_--m_aa_2 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/kinsol/serial/kinAnalytic_fp" "--m_aa" "2")
set_tests_properties(kinAnalytic_fp_--m_aa_2 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;98;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;0;")
add_test(kinAnalytic_fp_--m_aa_2_--delay_aa_2 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/kinsol/serial/kinAnalytic_fp" "--m_aa" "2" "--delay_aa" "2")
set_tests_properties(kinAnalytic_fp_--m_aa_2_--delay_aa_2 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;98;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;0;")
add_test(kinAnalytic_fp_--m_aa_2_--orth_aa_1 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/kinsol/serial/kinAnalytic_fp" "--m_aa" "2" "--orth_aa" "1")
set_tests_properties(kinAnalytic_fp_--m_aa_2_--orth_aa_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;98;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;0;")
add_test(kinAnalytic_fp_--m_aa_2_--orth_aa_2 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/kinsol/serial/kinAnalytic_fp" "--m_aa" "2" "--orth_aa" "2")
set_tests_properties(kinAnalytic_fp_--m_aa_2_--orth_aa_2 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;98;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;0;")
add_test(kinAnalytic_fp_--m_aa_2_--orth_aa_3 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/kinsol/serial/kinAnalytic_fp" "--m_aa" "2" "--orth_aa" "3")
set_tests_properties(kinAnalytic_fp_--m_aa_2_--orth_aa_3 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;98;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/kinsol/serial/CMakeLists.txt;0;")
