# CMake generated Testfile for 
# Source directory: /home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense
# Build directory: /home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackdense
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_lapackdense_10_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackdense/test_sunlinsol_lapackdense" "10" "0" "0")
set_tests_properties(test_sunlinsol_lapackdense_10_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;80;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;0;")
add_test(test_sunlinsol_lapackdense_100_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackdense/test_sunlinsol_lapackdense" "100" "0" "0")
set_tests_properties(test_sunlinsol_lapackdense_100_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;80;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;0;")
add_test(test_sunlinsol_lapackdense_500_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackdense/test_sunlinsol_lapackdense" "500" "0" "0")
set_tests_properties(test_sunlinsol_lapackdense_500_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;80;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;0;")
add_test(test_sunlinsol_lapackdense_1000_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackdense/test_sunlinsol_lapackdense" "1000" "0" "0")
set_tests_properties(test_sunlinsol_lapackdense_1000_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;80;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackdense/CMakeLists.txt;0;")
