# CMake generated Testfile for 
# Source directory: /home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband
# Build directory: /home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackband
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_lapackband_10_2_3_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackband/test_sunlinsol_lapackband" "10" "2" "3" "0" "0")
set_tests_properties(test_sunlinsol_lapackband_10_2_3_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;70;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;0;")
add_test(test_sunlinsol_lapackband_300_7_4_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackband/test_sunlinsol_lapackband" "300" "7" "4" "0" "0")
set_tests_properties(test_sunlinsol_lapackband_300_7_4_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;70;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;0;")
add_test(test_sunlinsol_lapackband_1000_8_8_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackband/test_sunlinsol_lapackband" "1000" "8" "8" "0" "0")
set_tests_properties(test_sunlinsol_lapackband_1000_8_8_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;70;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;0;")
add_test(test_sunlinsol_lapackband_5000_3_100_0_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/lapackband/test_sunlinsol_lapackband" "5000" "3" "100" "0" "0")
set_tests_properties(test_sunlinsol_lapackband_5000_3_100_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;70;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/lapackband/CMakeLists.txt;0;")
