# CMake generated Testfile for 
# Source directory: /home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band
# Build directory: /home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunmatrix/band
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunmatrix_band_10_2_3_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunmatrix/band/test_sunmatrix_band" "10" "2" "3" "0")
set_tests_properties(test_sunmatrix_band_10_2_3_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;0;")
add_test(test_sunmatrix_band_300_7_4_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunmatrix/band/test_sunmatrix_band" "300" "7" "4" "0")
set_tests_properties(test_sunmatrix_band_300_7_4_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;0;")
add_test(test_sunmatrix_band_1000_8_8_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunmatrix/band/test_sunmatrix_band" "1000" "8" "8" "0")
set_tests_properties(test_sunmatrix_band_1000_8_8_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;0;")
add_test(test_sunmatrix_band_5000_3_20_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunmatrix/band/test_sunmatrix_band" "5000" "3" "20" "0")
set_tests_properties(test_sunmatrix_band_5000_3_20_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunmatrix/band/CMakeLists.txt;0;")
