# CMake generated Testfile for 
# Source directory: /home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense
# Build directory: /home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/dense
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_dense_10_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/dense/test_sunlinsol_dense" "10" "0")
set_tests_properties(test_sunlinsol_dense_10_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
add_test(test_sunlinsol_dense_100_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/dense/test_sunlinsol_dense" "100" "0")
set_tests_properties(test_sunlinsol_dense_100_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
add_test(test_sunlinsol_dense_500_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/dense/test_sunlinsol_dense" "500" "0")
set_tests_properties(test_sunlinsol_dense_500_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
add_test(test_sunlinsol_dense_1000_0 "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/examples/sunlinsol/dense/test_sunlinsol_dense" "1000" "0")
set_tests_properties(test_sunlinsol_dense_1000_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/cmake/macros/SundialsAddTest.cmake;204;add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;75;sundials_add_test;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
