# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.27)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS SUNDIALS::core_static SUNDIALS::core_shared SUNDIALS::nvecserial_static SUNDIALS::nvecserial_shared SUNDIALS::nvecmanyvector_static SUNDIALS::nvecmanyvector_shared SUNDIALS::sunmatrixband_static SUNDIALS::sunmatrixband_shared SUNDIALS::sunmatrixdense_static SUNDIALS::sunmatrixdense_shared SUNDIALS::sunmatrixsparse_static SUNDIALS::sunmatrixsparse_shared SUNDIALS::sunlinsolband_static SUNDIALS::sunlinsolband_shared SUNDIALS::sunlinsoldense_static SUNDIALS::sunlinsoldense_shared SUNDIALS::sunlinsolpcg_static SUNDIALS::sunlinsolpcg_shared SUNDIALS::sunlinsolspbcgs_static SUNDIALS::sunlinsolspbcgs_shared SUNDIALS::sunlinsolspfgmr_static SUNDIALS::sunlinsolspfgmr_shared SUNDIALS::sunlinsolspgmr_static SUNDIALS::sunlinsolspgmr_shared SUNDIALS::sunlinsolsptfqmr_static SUNDIALS::sunlinsolsptfqmr_shared SUNDIALS::sunlinsollapackband_static SUNDIALS::sunlinsollapackband_shared SUNDIALS::sunlinsollapackdense_static SUNDIALS::sunlinsollapackdense_shared SUNDIALS::sunnonlinsolnewton_static SUNDIALS::sunnonlinsolnewton_shared SUNDIALS::sunnonlinsolfixedpoint_static SUNDIALS::sunnonlinsolfixedpoint_shared SUNDIALS::arkode_static SUNDIALS::arkode_shared SUNDIALS::cvode_static SUNDIALS::cvode_shared SUNDIALS::cvodes_static SUNDIALS::cvodes_shared SUNDIALS::ida_static SUNDIALS::ida_shared SUNDIALS::idas_static SUNDIALS::idas_shared SUNDIALS::kinsol_static SUNDIALS::kinsol_shared)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target SUNDIALS::core_static
add_library(SUNDIALS::core_static STATIC IMPORTED)

set_target_properties(SUNDIALS::core_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>"
)

# Create imported target SUNDIALS::core_shared
add_library(SUNDIALS::core_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::core_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
)

# Create imported target SUNDIALS::nvecserial_static
add_library(SUNDIALS::nvecserial_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::nvecserial_shared
add_library(SUNDIALS::nvecserial_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::nvecmanyvector_static
add_library(SUNDIALS::nvecmanyvector_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::nvecmanyvector_shared
add_library(SUNDIALS::nvecmanyvector_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixband_static
add_library(SUNDIALS::sunmatrixband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixband_shared
add_library(SUNDIALS::sunmatrixband_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixdense_static
add_library(SUNDIALS::sunmatrixdense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixdense_shared
add_library(SUNDIALS::sunmatrixdense_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixsparse_static
add_library(SUNDIALS::sunmatrixsparse_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixsparse_shared
add_library(SUNDIALS::sunmatrixsparse_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolband_static
add_library(SUNDIALS::sunlinsolband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared;SUNDIALS::sunmatrixband_shared"
)

# Create imported target SUNDIALS::sunlinsolband_shared
add_library(SUNDIALS::sunlinsolband_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared;SUNDIALS::sunmatrixband_shared"
)

# Create imported target SUNDIALS::sunlinsoldense_static
add_library(SUNDIALS::sunlinsoldense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared;SUNDIALS::sunmatrixdense_shared"
)

# Create imported target SUNDIALS::sunlinsoldense_shared
add_library(SUNDIALS::sunlinsoldense_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared;SUNDIALS::sunmatrixdense_shared"
)

# Create imported target SUNDIALS::sunlinsolpcg_static
add_library(SUNDIALS::sunlinsolpcg_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolpcg_shared
add_library(SUNDIALS::sunlinsolpcg_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspbcgs_static
add_library(SUNDIALS::sunlinsolspbcgs_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspbcgs_shared
add_library(SUNDIALS::sunlinsolspbcgs_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspfgmr_static
add_library(SUNDIALS::sunlinsolspfgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspfgmr_shared
add_library(SUNDIALS::sunlinsolspfgmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspgmr_static
add_library(SUNDIALS::sunlinsolspgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspgmr_shared
add_library(SUNDIALS::sunlinsolspgmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolsptfqmr_static
add_library(SUNDIALS::sunlinsolsptfqmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolsptfqmr_shared
add_library(SUNDIALS::sunlinsolsptfqmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsollapackband_static
add_library(SUNDIALS::sunlinsollapackband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsollapackband_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared;SUNDIALS::sunmatrixband_shared;/usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so"
)

# Create imported target SUNDIALS::sunlinsollapackband_shared
add_library(SUNDIALS::sunlinsollapackband_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsollapackband_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared;SUNDIALS::sunmatrixband_shared;/usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so"
)

# Create imported target SUNDIALS::sunlinsollapackdense_static
add_library(SUNDIALS::sunlinsollapackdense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsollapackdense_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared;SUNDIALS::sunmatrixdense_shared;/usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so"
)

# Create imported target SUNDIALS::sunlinsollapackdense_shared
add_library(SUNDIALS::sunlinsollapackdense_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsollapackdense_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared;SUNDIALS::sunmatrixdense_shared;/usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so"
)

# Create imported target SUNDIALS::sunnonlinsolnewton_static
add_library(SUNDIALS::sunnonlinsolnewton_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunnonlinsolnewton_shared
add_library(SUNDIALS::sunnonlinsolnewton_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunnonlinsolfixedpoint_static
add_library(SUNDIALS::sunnonlinsolfixedpoint_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunnonlinsolfixedpoint_shared
add_library(SUNDIALS::sunnonlinsolfixedpoint_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::arkode_static
add_library(SUNDIALS::arkode_static STATIC IMPORTED)

set_target_properties(SUNDIALS::arkode_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::arkode_shared
add_library(SUNDIALS::arkode_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::arkode_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::cvode_static
add_library(SUNDIALS::cvode_static STATIC IMPORTED)

set_target_properties(SUNDIALS::cvode_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::cvode_shared
add_library(SUNDIALS::cvode_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::cvode_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::cvodes_static
add_library(SUNDIALS::cvodes_static STATIC IMPORTED)

set_target_properties(SUNDIALS::cvodes_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::cvodes_shared
add_library(SUNDIALS::cvodes_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::cvodes_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::ida_static
add_library(SUNDIALS::ida_static STATIC IMPORTED)

set_target_properties(SUNDIALS::ida_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::ida_shared
add_library(SUNDIALS::ida_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::ida_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::idas_static
add_library(SUNDIALS::idas_static STATIC IMPORTED)

set_target_properties(SUNDIALS::idas_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::idas_shared
add_library(SUNDIALS::idas_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::idas_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::kinsol_static
add_library(SUNDIALS::kinsol_static STATIC IMPORTED)

set_target_properties(SUNDIALS::kinsol_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::kinsol_shared
add_library(SUNDIALS::kinsol_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::kinsol_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/include;/home/whitehole/PycharmProjects/master_thesis/sundials/sundials-7.0.0/src/sundials;/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Import target "SUNDIALS::core_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::core_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::core_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials/libsundials_core.a"
  )

# Import target "SUNDIALS::core_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::core_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::core_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sundials/libsundials_core.so.7.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_core.so.7"
  )

# Import target "SUNDIALS::nvecserial_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecserial_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/nvector/serial/libsundials_nvecserial.a"
  )

# Import target "SUNDIALS::nvecserial_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecserial_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/nvector/serial/libsundials_nvecserial.so.7.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_nvecserial.so.7"
  )

# Import target "SUNDIALS::nvecmanyvector_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecmanyvector_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/nvector/manyvector/libsundials_nvecmanyvector.a"
  )

# Import target "SUNDIALS::nvecmanyvector_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecmanyvector_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/nvector/manyvector/libsundials_nvecmanyvector.so.7.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_nvecmanyvector.so.7"
  )

# Import target "SUNDIALS::sunmatrixband_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunmatrix/band/libsundials_sunmatrixband.a"
  )

# Import target "SUNDIALS::sunmatrixband_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunmatrix/band/libsundials_sunmatrixband.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunmatrixband.so.5"
  )

# Import target "SUNDIALS::sunmatrixdense_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunmatrix/dense/libsundials_sunmatrixdense.a"
  )

# Import target "SUNDIALS::sunmatrixdense_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixdense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunmatrix/dense/libsundials_sunmatrixdense.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunmatrixdense.so.5"
  )

# Import target "SUNDIALS::sunmatrixsparse_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixsparse_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunmatrix/sparse/libsundials_sunmatrixsparse.a"
  )

# Import target "SUNDIALS::sunmatrixsparse_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixsparse_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunmatrix/sparse/libsundials_sunmatrixsparse.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunmatrixsparse.so.5"
  )

# Import target "SUNDIALS::sunlinsolband_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/band/libsundials_sunlinsolband.a"
  )

# Import target "SUNDIALS::sunlinsolband_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/band/libsundials_sunlinsolband.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolband.so.5"
  )

# Import target "SUNDIALS::sunlinsoldense_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsoldense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/dense/libsundials_sunlinsoldense.a"
  )

# Import target "SUNDIALS::sunlinsoldense_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsoldense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/dense/libsundials_sunlinsoldense.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsoldense.so.5"
  )

# Import target "SUNDIALS::sunlinsolpcg_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolpcg_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/pcg/libsundials_sunlinsolpcg.a"
  )

# Import target "SUNDIALS::sunlinsolpcg_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolpcg_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/pcg/libsundials_sunlinsolpcg.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolpcg.so.5"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/spbcgs/libsundials_sunlinsolspbcgs.a"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/spbcgs/libsundials_sunlinsolspbcgs.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolspbcgs.so.5"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/spfgmr/libsundials_sunlinsolspfgmr.a"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/spfgmr/libsundials_sunlinsolspfgmr.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolspfgmr.so.5"
  )

# Import target "SUNDIALS::sunlinsolspgmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/spgmr/libsundials_sunlinsolspgmr.a"
  )

# Import target "SUNDIALS::sunlinsolspgmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/spgmr/libsundials_sunlinsolspgmr.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolspgmr.so.5"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/sptfqmr/libsundials_sunlinsolsptfqmr.a"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/sptfqmr/libsundials_sunlinsolsptfqmr.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolsptfqmr.so.5"
  )

# Import target "SUNDIALS::sunlinsollapackband_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsollapackband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsollapackband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/lapackband/libsundials_sunlinsollapackband.a"
  )

# Import target "SUNDIALS::sunlinsollapackband_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsollapackband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsollapackband_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/lapackband/libsundials_sunlinsollapackband.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsollapackband.so.5"
  )

# Import target "SUNDIALS::sunlinsollapackdense_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsollapackdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsollapackdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/lapackdense/libsundials_sunlinsollapackdense.a"
  )

# Import target "SUNDIALS::sunlinsollapackdense_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsollapackdense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsollapackdense_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunlinsol/lapackdense/libsundials_sunlinsollapackdense.so.5.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsollapackdense.so.5"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunnonlinsol/newton/libsundials_sunnonlinsolnewton.a"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunnonlinsol/newton/libsundials_sunnonlinsolnewton.so.4.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunnonlinsolnewton.so.4"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunnonlinsol/fixedpoint/libsundials_sunnonlinsolfixedpoint.a"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/sunnonlinsol/fixedpoint/libsundials_sunnonlinsolfixedpoint.so.4.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunnonlinsolfixedpoint.so.4"
  )

# Import target "SUNDIALS::arkode_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::arkode_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::arkode_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/arkode/libsundials_arkode.a"
  )

# Import target "SUNDIALS::arkode_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::arkode_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::arkode_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/arkode/libsundials_arkode.so.6.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_arkode.so.6"
  )

# Import target "SUNDIALS::cvode_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::cvode_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::cvode_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/cvode/libsundials_cvode.a"
  )

# Import target "SUNDIALS::cvode_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::cvode_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::cvode_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/cvode/libsundials_cvode.so.7.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_cvode.so.7"
  )

# Import target "SUNDIALS::cvodes_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::cvodes_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::cvodes_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/cvodes/libsundials_cvodes.a"
  )

# Import target "SUNDIALS::cvodes_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::cvodes_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::cvodes_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/cvodes/libsundials_cvodes.so.7.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_cvodes.so.7"
  )

# Import target "SUNDIALS::ida_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::ida_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::ida_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/ida/libsundials_ida.a"
  )

# Import target "SUNDIALS::ida_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::ida_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::ida_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/ida/libsundials_ida.so.7.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_ida.so.7"
  )

# Import target "SUNDIALS::idas_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::idas_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::idas_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/idas/libsundials_idas.a"
  )

# Import target "SUNDIALS::idas_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::idas_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::idas_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/idas/libsundials_idas.so.6.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_idas.so.6"
  )

# Import target "SUNDIALS::kinsol_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::kinsol_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::kinsol_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/kinsol/libsundials_kinsol.a"
  )

# Import target "SUNDIALS::kinsol_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::kinsol_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::kinsol_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/whitehole/PycharmProjects/master_thesis/sundials/build-sundials-7.0.0/src/kinsol/libsundials_kinsol.so.7.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_kinsol.so.7"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
